apiVersion: v1
kind: Service
metadata:
  name: "nginx-external-name"
  namespace: "default"
spec:
  selector:
    app: nginx
  ports:
    - port: 80
  type: ExternalName
  externalName: "192.168.99.1"