apiVersion: v1
kind: Service
metadata:
  name: nginx-com-loadbalancer
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.103.16.120
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127