apiVersion: v1
kind: Service
metadata:
  name: "nginx-com-loadbalancer"
  namespace: "default"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.103.16.120
  type: LoadBalancer
  selector:
    app: "nginx"
status:
  loadBalancer:
    ingress:
      - ip: 192.168.0.164